version: '3'
services:
  spark-master:
    image: spark:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8081:8081"
      - "7077:7077"
    networks:
      - spark-network
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
    command: "/bin/sh /start-master.sh"
  spark-worker:
    image: spark:latest
    depends_on:
      - spark-master
    ports:
      - 8081
    networks:
      - spark-network
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8081"
    command: "/bin/sh /start-worker.sh"  
networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default