version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_CREATE_TOPICS: 'currency_rates:1:1;currency_assets:1:1'
  influxdb:
    image: 'influxdb:latest'
    ports:
      - '8087:8086'
    volumes:
      - 'influxdb_nfs:/var/lib/influxdb'
    environment:
      - 'INFLUXDB_DB=livingwallet'
      - 'INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}'
      - 'INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}'
  grafana:
    image: 'grafana/grafana:latest'
    ports:
      - '3000:3000'
    volumes:
      - 'grafana_nfs:/var/lib/grafana'
      - './grafana-provisioning/:/etc/grafana/provisioning'
    depends_on:
      - influxdb
    environment:
      - 'GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}'
      - 'GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}'
volumes:
  influxdb_nfs:
    external: true
  grafana_nfs:
    external: true